let data1 = [
    ['1','Brown Kiwi sp','Apterygiformes','Endemic'],
    ['2','Yellow-eyed Penguin','Sphenisciformes','Endemic'],
    ['3','Little Blue Penguin','Sphenisciformes','Native'],
    ['4','Fiordland Crested Penguin','Sphenisciformes','Endemic'],
    ['5','Australasian Gannet','Suliformes','Native'],
    ['6','Black Shag','Suliformes','Native'],
    ['7','Pied Shag','Suliformes','Native'],
    ['8','White-faced Heron','Pelecaniformes','Native'],
    ['9','Black Swan','Anseriformes','Introduced'],
    ['10','Canada Goose','Anseriformes','Introduced'],
    ['11','Paradise Shelduck','Anseriformes','Endemic'],
    ['12','Blue Duck','Anseriformes','Endemic'],
    ['13','Mallard','Anseriformes','Introduced'],
    ['14','Grey Teal','Anseriformes','Native'],
    ['15','Brown Teal','Anseriformes','Endemic'],
    ['16','Australasian Shoveler','Anseriformes','Native'],
    ['17','New Zealand Scaup','Anseriformes','Endemic'],
    ['18','Swamp Harrier','Accipitriformes','Native'],
    ['19','New Zealand Falcon','Falconiformes','Endemic'],
    ['20','Brown Quail','Galliformes','Introduced'],
    ['21','Common Pheasant','Galliformes','Introduced'],
    ['22','California Quail','Galliformes','Introduced'],
    ['23','Weka','Gruiformes','Endemic'],
    ['24','Banded Rail','Gruiformes','Native'],
    ['25','Spotless Crake','Gruiformes','Native'],
    ['26','Pukeko','Gruiformes','Native'],
    ['27','Coot','Gruiformes','Native'],
    ['28','Bar-tailed Godwit','Charadriiformes','Native'],
    ['29','Red Knot','Charadriiformes','Native'],
    ['30','South Island Pied Oystercatcher','Charadriiformes','Endemic'],
    ['31','Variable Oystercatcher','Charadriiformes','Endemic'],
    ['32','Pied Stilt','Charadriiformes','Native'],
    ['33','New Zealand Dotterel','Charadriiformes','Endemic'],
    ['34','Banded Dotterel','Charadriiformes','Endemic'],
    ['35','Wrybill','Charadriiformes','Endemic'],
    ['36','Masked Lapwing','Charadriiformes','Native'],
    ['37','Black-backed Gull','Charadriiformes','Native'],
    ['38','Red-billed Gull','Charadriiformes','Native'],
    ['39','Black-billed Gull','Charadriiformes','Endemic'],
    ['40','Caspian Tern','Charadriiformes','Native'],
    ['41','White-fronted Tern','Charadriiformes','Native'],
    ['42','Black-fronted tern','Charadriiformes','Native'],
    ['43','Kereru','Columbiformes','Endemic'],
    ['44','Spotted Dove','Columbiformes','Introduced'],
    ['45','Barbary Dove','Columbiformes','Introduced'],
['46','Kaka','Psittaciformes','Endemic'],
    ['47','Kea','Psittaciformes','Endemic'],
    ['48','Eastern Rosella','Psittaciformes','Introduced'],
    ['49','Red-crowned Parakeet','Psittaciformes','Endemic'],
    ['50','Yellow-crowned Parakeet','Psittaciformes','Endemic'],
    ['51','Shining Cuckoo','Cuculiformes','Native'],
    ['52','Long-tailed Cuckoo','Cuculiformes','Endemic'],
    ['53','Morepork','Strigiformes','Native'],
    ['54','Sacred Kingfisher','Coraciiformes','Native'],
    ['55','Rifleman','Passeriformes','Endemic'],
    ['56','Rock Wren','Passeriformes','Endemic'],
    ['57','Skylark','Passeriformes','Introduced'],
    ['58','Welcome Swallow','Passeriformes','Native'],
    ['59','New Zealand Pipit','Passeriformes','Native'],
    ['60','Dunnock','Passeriformes','Introduced'],
    ['61','Blackbird','Passeriformes','Introduced'],
    ['62','Song Thrush','Passeriformes','Introduced'],
    ['63','Fernbird','Passeriformes','Endemic'],
    ['64','Whitehead','Passeriformes','Endemic'],
    ['65','Yellowhead','Passeriformes','Endemic'],
    ['66','Brown Creeper','Passeriformes','Endemic'],
    ['67','Grey Warbler','Passeriformes','Endemic'],
    ['68','Fantail','Passeriformes','Native'],
    ['69','Tomtit','Passeriformes','Endemic'],
    ['70','Robin','Passeriformes','Endemic'],
    ['71','Silvereye','Passeriformes','Native'],
    ['72','Hihi','Passeriformes','Endemic'],
    ['73','Bellbird','Passeriformes','Endemic'],
    ['74','Tui','Passeriformes','Endemic'],
    ['75','Yellowhammer','Passeriformes','Introduced'],
    ['76','Chaffinch','Passeriformes','Introduced'],
    ['77','Greenfinch','Passeriformes','Introduced'],
    ['78','Goldfinch','Passeriformes','Introduced'],
    ['79','Redpoll','Passeriformes','Introduced'],
    ['80','House Sparrow','Passeriformes','Introduced'],
    ['81','Starling','Passeriformes','Introduced'],
    ['82','Indian Myna','Passeriformes','Introduced'],
    ['83','Kokako','Passeriformes','Endemic'],
    ['84','North Island Saddleback','Passeriformes','Endemic'],
    ['85','South Island Saddleback','Passeriformes','Endemic'],
    ['86','Magpie','Passeriformes','Introduced']
]
function getData(){
var check = document.getElementById("content");
var da ="";
data1.forEach(element => {
da += "<tr><td>" + element[0]  + "</td><td>" + element[1]  + "</td><td>" + element[2]  + "</td><td>" + element[3]  + "</td></tr>";
});
check.innerHTML = da;
}
getData();
